numbers=[5, 2, 1, 1, 7, 4]
numbers.append(20)
print(numbers)
numbers.insert(2, 10)
print(numbers)
numbers.remove(5)
print(numbers)
num=numbers.pop()
print(numbers)
print(num)
print(numbers.index(10))
# print(numbers.index(50))
# ValueError: 50 is not in list
print(50 in numbers)
print(numbers.count(1))
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers) #sort in descending
numbers2=numbers.copy()
print(numbers2)
numbers2.append(10)
print(numbers2)
numbers.clear()
print(numbers)